### ISSUE TITLE
Default host should point to production location of SuperSaaS

### ISSUE THREAD

**Issue by jgadelange** [SuperSaaS/supersaas-python-api-client#1]
This is not so much a bug, but an inconvenience and something missing in the README.

I believe the default host should point to the production environment of SuperSaaS instead of pointing to `localhost:3000` so the default configuration is usable in production environments. At least a reference to the configuration option of host should be added tot the README.

**Comment by TertiumQuid** [comment]
Excellent point. The dev host default was an oversight, and the default option (as of version 10.0.1) is now using the production API URL.
