### ISSUE TITLE
Examples are empty

### ISSUE THREAD

**Issue by jgadelange** [SuperSaaS/supersaas-python-api-client#2]
Examples dir contains only empty files

**Comment by TertiumQuid** [comment]
Indeed! The examples are being postponed until the next major update to the client which would likely render them moot; however I confusingly left the stub files in the project.

**Comment by jgadelange** [comment]
Any timeline on that next release? The current version seems really broken (see #3 and #4)

**Comment by TertiumQuid** [comment]
Thanks for the PRs. I'll take a look, test against Python versions, and likely merge this afternoon.
