### ISSUE TITLE
Client is broken

### ISSUE THREAD

**Issue by jgadelange** [SuperSaaS/supersaas-python-api-client#3]
The `request()` method in the `Client` is broken ([line140](https://github.com/SuperSaaS/supersaas-python-api-client/blob/master/SuperSaaS/Client.py#L140))

`json.load()` expects a file like argument and gets a string now. Two options to fix this are:
1. Change to `json.load(res)`
2. Change to `json.loads(res.read())`

**Comment by TertiumQuid** [comment]
Thanks again! The change won't quite work as is because the client needs to support both 2.7 and 3, which I think can be handled like so:

```
try:
    basestring
except NameError:
    basestring = str
...
data = json.loads(res) if isinstance(res, basestring) else json.loads(res.read())
```

That fix is in now 0.10.2, and available on PyPi.
